CREATE DATABASE IF NOT EXISTS my_art_database;
USE my_art_database;


CREATE TABLE Exhibitions (
  ExhibitionID INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL
);

CREATE TABLE Artists (
  ArtistID INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Biography TEXT,
  Portfolio TEXT,
  ContactInfo VARCHAR(255)
);


CREATE TABLE Users (
  UserID INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(255) NOT NULL UNIQUE,
  Password VARCHAR(255) NOT NULL,
  Role VARCHAR(255) NOT NULL
);


CREATE TABLE Artworks (
  ArtworkID INT PRIMARY KEY AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  ArtistID INT NOT NULL,
  Medium VARCHAR(255) NOT NULL,
  Dimensions VARCHAR(255),
  CreationDate DATE NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  ImagePath VARCHAR(255),
  ExhibitionID INT,
  FOREIGN KEY (ArtistID) REFERENCES Artists(ArtistID),
  FOREIGN KEY (ExhibitionID) REFERENCES Exhibitions(ExhibitionID)
);


CREATE TABLE Transactions (
  TransactionID INT PRIMARY KEY AUTO_INCREMENT,
  UserID INT NOT NULL,
  ArtworkID INT NOT NULL,
  TransactionDate DATE NOT NULL,
  TransactionAmount DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (ArtworkID) REFERENCES Artworks(ArtworkID)
);

